# add_newline = false
#
# command_timeout=2000
#
# [line_break]
# disabled = false

# add_newline = false
# command_timeout = 200
# format = "[$directory$git_branch$git_status]($style)$character"
#
# [character]
# error_symbol = "[✗](bold cyan)"
# success_symbol = "[❯](bold cyan)"
#
# [directory]
# truncation_length = 2
# truncation_symbol = "…/"
# repo_root_style = "bold cyan"
# repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
#
# [git_branch]
# format = "[$branch]($style) "
# style = "italic cyan"
#
# [git_status]
# format     = '[$all_status]($style)'
# style      = "cyan"
# ahead      = "⇡${count} "
# diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
# behind     = "⇣${count} "
# conflicted = " "
# up_to_date = " "
# untracked  = "? "
# modified   = " "
# stashed    = ""
# staged     = ""
# renamed    = ""
# deleted    = ""

format ="""
$username\
$hostname\
$character\
$directory\
$git_branch\
$git_state\
$git_status\
"""

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Shows the shows the current user name
[username]
format = '[\[[$user](white)](blue)'
# format = '[\[[m](white)](blue)'
show_always = true
disabled = false

# Shows the current host name
[hostname]
ssh_only = false
format = '[[@](red)[$hostname](white)\] ](blue)'
trim_at = ""
disabled = false

# Replace the "❯" symbol in the prompt with "✗" or "❯❯❯" or "×" or "λ" or "➜"
[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"
disabled = false

# Shows the current directory
[directory]
style = "cyan"
truncate_to_repo = true
truncation_length = 1
truncation_symbol = ""
disabled = false

[git_branch]
format = '[\([$symbol $branch(:$remote_name)](purple)\) ](blue)'
symbol = "[](yellow)"

[git_status]
format = "([$all_status$ahead_behind$diverged]($style) )"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "U"
modified = "~"
staged = "+"
renamed = "»"
deleted = "-"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
format = "[$symbol$version ]($style)"
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
format = "[$symbol$version ]($style)"
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[lua]
format = "[$symbol$version ]($style)"
symbol = " "

[c]
format = "[$symbol$version ]($style)"
symbol = " "
